### ISSUE TITLE
[Feat] 홈뷰 신상품 페이지 구현

### ISSUE THREAD

**Issue by HELLOHIDI** [HELLOHIDI/HidiKurly#5]
## 🛠 Issue
- 홈뷰 신상품 페이지 구현

## 📋 To-do
- [ ] 마크 문법 적용시키기
- [ ] 동적 셀 통해서 카테고리 셀 구현하기
- [ ] 카테고리 필터 부분 UI 구현하기
- [ ] 컬렉션 뷰 통해서 상품들 구현하기
- [ ] 동적 셀 관련 아티클 작성
- [ ] 그 높이 조절하는 부분 아티클 작성
